version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myblog
      MYSQL_USER: testuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    container_name: myweb-database
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: my_back
      dockerfile: Dockerfile
    volumes:
      - ./my_back:/usr/src/app
    environment:
      - NODE_ENV=development
    container_name: myweb-api
    depends_on:
      - mysql

  frontend:
    build:
      context: my_front
      dockerfile: Dockerfile
    container_name: myweb-web
    volumes:
      - ./my_front:/usr/src/app

volumes:
  mysql-data:
