version: '3'

services:
  backend:
    build:
      context: ./my_nodejs_blog
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./my_nodejs_blog:/usr/src/app
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./my-react-blog
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./my-react-blog:/usr/src/app

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myblog
      MYSQL_USER: testuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: